### ISSUE TITLE
Fatal error: Interface 'JsonSerializable' not found

### ISSUE THREAD

**Issue by krekos** [FoxyImages/php-build#2]
Zdravím chtěl sem použít Image na náš Nette projekt. Ale dostává výše zmíněnou chybu. Přikládám konfiguraci CI a přesný výpis.

`Fatal error: Interface 'JsonSerializable' not found in /builds/MyRepo/MyProject/vendor/nette/utils/src/Utils/DateTime.php on line 17`

``` yaml
image: sunfoxcz/php-build:5.6
cache:
    paths:
        - vendor/
before_script:
    - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader
    - mkdir temp
test:
    script:
        - vendor/bin/tester tests -p php --colors 1
    only:
        - feature/Nette_Tester
```
